# Generated by Django 4.0.6 on 2022-07-27 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genree', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('genre', models.ForeignKey(default='Mohsin', on_delete=django.db.models.deletion.CASCADE, to='Test.genre')),
            ],
        ),
    ]
